version: 2
jobs:
  test-api:
    working-directory: './api'
    machine: true
    branches:
      only:
        - develop
    steps:
      - checkout
      - run:
          name: Checkout develop
          command: git checkout develop
      - run:
          name: Install
          command: cd api && npm install
      - run: 
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: npm run script coveralls